name: Commit Check

on: [push, pull_request]

jobs:
  always-pass:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Dummy step
        run: echo "This always passes"
